// Package main generated by 'freedom new-project spider'
package main

import (
	"deeptrade/conf"
	"deeptrade/task"
	tradeflow "deeptrade/task/trade_flow"
	"deeptrade/utils"
	"fmt"
	"log"
	"time"
)

func main() {
	// 启动日志
	log.Println("==========================================")
	log.Printf("启动ETH期货量化交易系统, 当前环境: %s\n", conf.Get().Binance.CurrentEnvironment)
	log.Printf("定时器: 每%d秒执行一次\n", conf.Get().Trading.TriggerTime*60)
	log.Println("==========================================")
	task.InitOffSystem()
	log.Println("[系统] 分析和准备趋势数据-大约8-10分钟")
	tradeflow.RunFetch(task.IsWork) //拉取数据
	for {
		working := task.IsWork()
		if !working {
			time.Sleep(15 * time.Minute)
			continue
		}
		log.Println("开始新的交易周期...")

		// 直接执行量化交易
		if err := task.RunQuantitativeTrading(); err != nil {
			log.Printf("量化交易执行失败: %v, 30秒后重试", err)
			utils.SendHtmlMail("DeepTrade通知", fmt.Sprintf("错误信息 %v", err))
			time.Sleep(30 * time.Second)
			continue
		}

		log.Printf("本轮交易周期结束，等待%d秒...\n", task.GetSleepSec())
		time.Sleep(time.Duration(task.GetSleepSec()) * time.Second)
	}
}
